### ISSUE TITLE
app crashed when compile

### ISSUE THREAD

**Issue by KAM202** [TheLimeGlass/StreamElements-Java-API#10]
Hey. I try add ur api to my android studio project. When i want to compile and test app i have error:
`java.lang.NoClassDefFoundError: Failed resolution of: Lorg/reflections/Reflections;
        at me.limeglass.streamelements.internals.handlers.ElementsReaderHandler.load(ElementsReaderHandler.java:47)
        at me.limeglass.streamelements.internals.StreamElementsClient.<init>(StreamElementsClient.java:35)
        at me.limeglass.streamelements.api.StreamElementsBuilder.build(StreamElementsBuilder.java:110)`

What i'm doing wrong?

**Comment by TheLimeGlass** [comment]
Did you shade the dependencies? Are you using Gradle or maven? If not you can look on GitHub for the software called Reflections, and use Jitpack.io to grab it for whatever your dependency manager is. Let me know for updates.

**Comment by KAM202** [comment]
I'm using maven. Already i have added ur git project. My MainActivity code:
`instance = new StreamElementsBuilder()
                .withAccountID(accoundID)
                .registerListeners(EventListenerExample.class)
                .withToken(token)
                .withConnectionTimeout(10000)
                .build();`

returning error:
`E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.kam202.streamelements, PID: 9991
    java.lang.NoSuchMethodError: No static method metafactory(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodHandle;Ljava/lang/invoke/MethodType;)Ljava/lang/invoke/CallSite; in class Ljava/lang/invoke/LambdaMetafactory; or its super classes (declaration of 'java.lang.invoke.LambdaMetafactory' appears in /apex/com.android.runtime/javalib/core-oj.jar)
        at me.limeglass.streamelements.internals.handlers.ElementsReaderHandler.load(ElementsReaderHandler.java:50)
        at me.limeglass.streamelements.internals.StreamElementsClient.<init>(StreamElementsClient.java:35)
        at me.limeglass.streamelements.api.StreamElementsBuilder.build(StreamElementsBuilder.java:110)
        at com.kam202.streamelements.MainActivity.onCreate(MainActivity.java:40)
        at android.app.Activity.performCreate(Activity.java:8049)
        at android.app.Activity.performCreate(Activity.java:8037)`

I must increase min api from 19 to 26 becouse I had
`MethodHandle.invoke and MethodHandle.invokeExact are only supported starting with Android O (--min-api 26)
` 

So.. what's wrong?

EDIT:
i'm added in build.grandle
`compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }`

and in main class
`StrictMode.ThreadPolicy policy = new StrictMode.ThreadPolicy.Builder().permitAll().build();
        StrictMode.setThreadPolicy(policy);`
now im getting
`java.lang.RuntimeException: Unable to start activity ComponentInfo{com.kam202.streamelements/com.kam202.streamelements.MainActivity}: java.util.NoSuchElementException: No value present
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3752)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3923)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:91)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2368)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:213)
        at android.app.ActivityThread.main(ActivityThread.java:8113)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
     Caused by: java.util.NoSuchElementException: No value present`

Code ^:
`Points points = instance.getUserPoints("kam203");
        User user = points.getUser();
        TextView x = findViewById(R.id.XD);
        x.setText(user.getName()
                + " is #" + points.getRank() + " in the leaderboard"
                + " with " + points.getCurrentPoints() + " points! PogChamp");`

and event's like onConnect, on Connection and onAuthenticated not working (none log's in debug)
